version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      # - api-service

  auth-service:
    image: auth
    # environment:
    #   - NODE_ENV=production
    expose:
      - "3000"

  api-service:
    image: nest-app
    environment:
      - NODE_ENV=production
    expose:
      - "4000"

