version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: joonbee-test-server
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C.UTF-8 --lc-ctype=C.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: joonbee_redis_container
    command: redis-server --requirepass 1234
    ports:
      - "6379:6379"

volumes:
  pgdata:
