version: '3'

services:
  redis-pub:
    image: redis:latest
    container_name: joonbee_redis_container
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6378:6379"
